name: latex-build-and-release
description: Builds a PDF file from LaTeX source and publishes it as asset in a release.
author: TemplatesHub
branding: 
  icon: 'file-text'
  color: 'green'
inputs:
  tex-entry-point:
    description: 'Entry point .tex file'
    type: string
    required: false
    default: 'main'
  pdf-name:
    description: 'Final PDF file name'
    type: string
    required: false
    default: '${{ github.event.repository.name }}'
runs:
  using: 'composite'
  steps:
    - name: "Install texlive"
      run: sudo apt-get -y install texlive-full
    - name: "Build PDF file"
      run: pdflatex ${{ github.event.inputs.tex-entry-point }}.tex
    - name: "Rename PDF file"
      run: mv ${{ github.event.inputs.tex-entry-point }}.pdf "${{ github.event.inputs.pdf-name }} ${{ github.ref_name }}.pdf"
    - name: "Upload PDF as artifact in release"
      run: gh release upload ${{ github.ref_name }} "${{ github.event.inputs.pdf-name }} ${{ github.ref_name }}.pdf"