name: LaTeX build and release
on:
  workflow_call:
    inputs:
      tex-entry-point:
        description: 'Entry point .tex file'
        type: string
        required: true
      pdf-name:
        description: 'Final PDF file name'
        type: string
        required: true

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: ${{ github.event.inputs.tex-entry-point }}.tex
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode --shell-escape
      - name: Rename file
        run: mv ${{ github.event.inputs.tex-entry-point }}.pdf "${{ github.event.inputs.pdf-name }} ${{ github.ref_name }}.pdf"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ github.event.inputs.pdf-name }} ${{ github.ref_name }}.pdf